### ISSUE TITLE
libwebsockets does not build on Ubuntu 22.04

### ISSUE THREAD

**Issue by oschwartz10612** [usdot-fhwa-OPS/V2X-Hub#432]
libwebsockets does not build on Ubuntu 22.04. See the below errors:

```
#0 12.50 /home/V2X-Hub/ext/libwebsockets/lib/tls/openssl/openssl-server.c: In function 'lws_tls_server_certs_load':
#0 12.50 /home/V2X-Hub/ext/libwebsockets/lib/tls/openssl/openssl-server.c:396:9: error: 'EC_KEY_new_by_curve_name' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
#0 12.50   396 |         ecdh = EC_KEY_new_by_curve_name(ecdh_nid);
#0 12.50       |         ^~~~
#0 12.50 In file included from /usr/include/openssl/x509.h:33,
#0 12.50                  from /usr/include/openssl/ssl.h:31,
#0 12.50                  from /home/V2X-Hub/ext/libwebsockets/include/libwebsockets.h:229,
#0 12.50                  from /home/V2X-Hub/ext/libwebsockets/lib/core/private.h:126,
#0 12.50                  from /home/V2X-Hub/ext/libwebsockets/lib/tls/openssl/openssl-server.c:22:
#0 12.50 /usr/include/openssl/ec.h:998:31: note: declared here
#0 12.50   998 | OSSL_DEPRECATEDIN_3_0 EC_KEY *EC_KEY_new_by_curve_name(int nid);
#0 12.50       |                               ^~~~~~~~~~~~~~~~~~~~~~~~
#0 12.50 /home/V2X-Hub/ext/libwebsockets/lib/tls/openssl/openssl-server.c:402:9: error: 'EC_KEY_free' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
#0 12.50   402 |         EC_KEY_free(ecdh);
#0 12.50       |         ^~~~~~~~~~~
#0 12.50 In file included from /usr/include/openssl/x509.h:33,
#0 12.50                  from /usr/include/openssl/ssl.h:31,
#0 12.50                  from /home/V2X-Hub/ext/libwebsockets/include/libwebsockets.h:229,
#0 12.50                  from /home/V2X-Hub/ext/libwebsockets/lib/core/private.h:126,
#0 12.50                  from /home/V2X-Hub/ext/libwebsockets/lib/tls/openssl/openssl-server.c:22:
#0 12.50 /usr/include/openssl/ec.h:1003:28: note: declared here
#0 12.50  1003 | OSSL_DEPRECATEDIN_3_0 void EC_KEY_free(EC_KEY *key);
#0 12.50       |                            ^~~~~~~~~~~
#0 12.51 /home/V2X-Hub/ext/libwebsockets/lib/tls/openssl/openssl-server.c:444:9: error: 'EVP_PKEY_get1_EC_KEY' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
#0 12.51   444 |         EC_key = EVP_PKEY_get1_EC_KEY(pkey);
#0 12.51       |         ^~~~~~
#0 12.51 In file included from /usr/include/openssl/x509.h:29,
#0 12.51                  from /usr/include/openssl/ssl.h:31,
#0 12.51                  from /home/V2X-Hub/ext/libwebsockets/include/libwebsockets.h:229,
#0 12.51                  from /home/V2X-Hub/ext/libwebsockets/lib/core/private.h:126,
#0 12.51                  from /home/V2X-Hub/ext/libwebsockets/lib/tls/openssl/openssl-server.c:22:
#0 12.51 /usr/include/openssl/evp.h:1374:19: note: declared here
#0 12.51  1374 | struct ec_key_st *EVP_PKEY_get1_EC_KEY(EVP_PKEY *pkey);
#0 12.51       |                   ^~~~~~~~~~~~~~~~~~~~
#0 12.51 /home/V2X-Hub/ext/libwebsockets/lib/tls/openssl/openssl-server.c:452:9: error: 'EC_KEY_free' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
#0 12.51   452 |         EC_KEY_free(EC_key);
#0 12.51       |         ^~~~~~~~~~~
#0 12.51 In file included from /usr/include/openssl/x509.h:33,
#0 12.51                  from /usr/include/openssl/ssl.h:31,
#0 12.51                  from /home/V2X-Hub/ext/libwebsockets/include/libwebsockets.h:229,
#0 12.51                  from /home/V2X-Hub/ext/libwebsockets/lib/core/private.h:126,
#0 12.51                  from /home/V2X-Hub/ext/libwebsockets/lib/tls/openssl/openssl-server.c:22:
#0 12.51 /usr/include/openssl/ec.h:1003:28: note: declared here
#0 12.51  1003 | OSSL_DEPRECATEDIN_3_0 void EC_KEY_free(EC_KEY *key);
#0 12.51       |                            ^~~~~~~~~~~
#0 12.60 cc1: all warnings being treated as errors
#0 12.60 make[2]: *** [CMakeFiles/websockets.dir/build.make:762: CMakeFiles/websockets.dir/lib/tls/openssl/openssl-server.c.o] Error 1
#0 12.60 make[1]: *** [CMakeFiles/Makefile2:92: CMakeFiles/websockets.dir/all] Error 2
#0 12.60 make: *** [Makefile:156: all] Error 2

```

**Comment by rob-baily** [comment]
This is because the libwebsockets library is out of sync with the openssl version that comes with Ubuntu 22.

**Comment by rob-baily** [comment]
@oschwartz10612 As noted in #458 the changes are now in the main develop branch that should should work with Ubuntu 22.  We are no longer compiling a custom version of libwebsockets as the versions that come with Ubuntu 20 or work as is.
